Optional params
fram-lang/dbl pull request #122
Opened 2024-06-11 04:58 UTC by Tagada14

Introduces optional parameters.
The implementation is finished and appears to be working.

Things left to do:
- Add missing comments
- Add tests
- Check for Col limit
- Potentially rewrite parts of the code to make it more readable

2024-06-29 13:32 UTC, Tagada14 commented
@ppolesiuk The PR is ready for review

2024-08-07 13:31 UTC, ppolesiuk requested changes
The implementation looks very solid. Thanks for good job! There are some minor things that should be addressed. Then, I will merge these changes into upstream.

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/ExprUtils.ml
> +    { T.pos = e.pos; T.data = T.EApp(e, arg) }
This implementation suffers problem similar to #11: implicit arguments are not reinstatiated when function has polymorphic argument. Here is an example code that exhibit this behavior:
```
let foo (f : {?x:Int} -> Unit ->[] Int) = f {x=42} ()
let bar {?x} =
  match x with
  | None => 0
  | Some y => y
  end

let z = foo bar // z is equal to 0, but intuitively it should give 42
```
We are not going to fix it now. We will fix it together with #11.

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/Pattern.ml
> +
Indentation of this piece of code should be increased

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/Pattern.ml
> +  assert (T.Scheme.is_monomorphic sch);
There is no invariant that ensure this. User can write an invalid program that violates this assertion:
```
let foo {?x:{x:Int} -> Int} = x
```

The implementation should check if this scheme is monomorphic, and if not, display a readable error for the user.

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/Pattern.mli
> +  Env.t -> S.arg -> Env.t * T.pattern * T.scheme * ret_effect
Should this function be public? I didn't find any place where it was used outside this module.

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/PolyExpr.ml
> +          (n, e, T.Scheme.of_type tp, r_eff1)
The logic behind this part of code has grown so it is hard to follow. Maybe it could by improved by a simple comment explaining what's going on.

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/PreludeTypes.ml
> +          (fun (ctor_decl : T.ctor_decl) -> String.compare ctor_decl.ctor_name "Some" == 0)
It's easier to use standard equality to compare strings: `ctor_decl.ctor_name = "Some"`

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/PreludeTypes.ml
> +                 [ expr_arg ] ))
Do we know, that `Some` constructor expects one parameter? Should it be checked? I know, such errors should never happen for casual user, but ...

2024-08-07 13:31 UTC, ppolesiuk commented on src/TypeInference/TypeUtils.ml
> +          | T.NOptionalVar x -> Env.add_mono_var env x sch.sch_body
`add_mono_var env x sch.sch_body` and `add_poly_var env x sch` are equivalent for monomorphic types (for polymorphic types the former doesn't have any sense). Maybe these two clauses could be merged?

2024-08-07 13:31 UTC, ppolesiuk commented on test/err/tc_0007_missingOptionTypeDef.fram
In negative tests, we try to write some comments with regular expressions that should be matched with the stderr output (see other tests).

2024-08-07 13:31 UTC, ppolesiuk commented on test/ok/ok0109_optionalParams.fram
> +end
We should format tests correctly. This match expression should be indented. The next (in lines 18-21) should be fixed too.

2024-08-28 13:42 UTC, ppolesiuk commented on src/TypeInference/PreludeTypes.ml
> +                 [ expr_arg ] ))
I tried to implement it, checking correct type of `Some` and `None` constructor. The code is too complicated for a thing that should never happen, so I decided to not address this issue. Internal type error is good enough.

2024-08-28 19:11 UTC, merged