String interpolation
fram-lang/dbl pull request #123
Opened 2024-06-12 17:26 UTC by wojpok

This is my take on string interpolation.

This change requires additional state in lexer, as discussed already. Most of the work is made while "desugaarring" though.
 
Since optional parameters are still not implemented, it is a draft pull request and will be updated later. 
For demonstration purposes I added a new ```toFormatted``` method, that is invoked while interpolating strings.

2025-04-22 14:17 UTC, ppolesiuk requested changes
Thanks! The implementation looks good, but has several flaws.
- Lexer is buggy. See comments below.
- Changes to standard library are too complicated for me.
- Code formatting could be improved. There are lines longer than 80 columns.
- I'm not sure if the implementation works well in REPL. I didn't find a call to `Lexer.reset` in REPL related functions.
- Position tracking in `Desugar` could be improved.

BTW, I think we can rename `toFormatted` method to simpler `format`. Do you agree?

Since this PR was open for a long time, I can fix the issues mentioned in this review, and adapt it to the new codebase.

2025-04-26 17:03 UTC, wojpok commented
I have resolved most of the issues. We definitely should discuss how to approach formatting.  I have decided to use `toString` method if no format argument is provided and `format` method otherwise. I think more elaborate formatting could be implemented alongside pretty printing library

2025-07-02 08:25 UTC, ppolesiuk requested changes
There are still some minor issues with desugaring. For other parts of this PR, I think they are ready for merge.

2025-07-02 08:25 UTC, ppolesiuk commented on code.rkt
This file looks like dump from some debugging. It should not be present in the repository.

2025-07-02 08:25 UTC, ppolesiuk commented on src/Eval/External.ml
> +    "dbl_chrListToStr", list_fun to_char (fun xs -> VStr (List.to_seq xs |> String.of_seq));
This line is too long

2025-07-02 08:25 UTC, ppolesiuk commented on src/DblParser/Desugar.ml
> +      let mth = make (Raw.EMethod (expr, "format")) in
Using `make (Raw.EMethod ...)` gives us imprecise information about position. For instance:
```
> data T = A ;;
> "\{ A }" ;;
fatal error: Type T has no method named format
   | "\{ A }" ;;
   | ^^^^^^^^
   |
>
```
It would be better to point to `expr` instead of the whole interpolation.

2025-07-02 08:25 UTC, ppolesiuk commented on src/DblParser/Desugar.ml
> +      let fld = make (Raw.FldNameVal (Raw.NOptionalVar "fmt", format)) in
It think the point of using optional arguments here is to omit them when they are not provided instead of explicitly provide `None`.

2025-07-02 14:34 UTC, wojpok commented
Issues have been fixed. I also noticed that formatting argument had have wrong position assigned in case of type error. I fixed it by attaching argument's position to `Some` constructor

2025-07-03 04:25 UTC, ppolesiuk approved these changes
Now the PR is ready to merge. Thanks!

In the last commit I slightly improved position tracking and changed `fmt` parameter to regular (`fmt = e` instead of `?fmt = Some e`). For optional parameters it means the same, but it allows `format` methods with mandatory `fmt`. Moreover, the code is simpler.

2025-07-03 04:26 UTC, merged