Change implicits syntax to tilde
fram-lang/dbl pull request #146
Opened 2024-10-11 10:35 UTC by Florian3k

2024-10-15 05:55 UTC, MinionJakub commented
It's look good. I haven't seen any problems.

2024-10-22 07:10 UTC, MinionJakub approved these changes
Everything looks good.

2024-10-23 14:06 UTC, ppolesiuk requested changes
The new syntax introduces a slight lexical ambiguity, that should be addressed. The rest looks ok (I've checked using grep, and fixed some comments).

2024-10-25 04:18 UTC, ppolesiuk commented on src/DblParser/Lexer.mll
> +  | '~' lid_start var_char* as x { YaccParser.TLID x }
We agreed to disallow `~` and `?` operators. This will be done as a separate issue (#150), so now the PR is ready to merge.

2024-10-25 04:18 UTC, ppolesiuk approved these changes

2024-10-25 04:20 UTC, merged